"""empty message

Revision ID: 070321649bf3
Revises: a8a2594da8fa
Create Date: 2018-07-08 09:04:33.606492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070321649bf3'
down_revision = 'a8a2594da8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumb_ups',
    sa.Column('thumbers_id', sa.Integer(), nullable=True),
    sa.Column('thumbed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thumbed_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['thumbers_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumb_ups')
    # ### end Alembic commands ###
