"""empty message

Revision ID: 9b8f23b36a0b
Revises: f86fb6923973
Create Date: 2018-07-10 23:21:38.460607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8f23b36a0b'
down_revision = 'f86fb6923973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('language', sa.String(length=5), nullable=True))
    op.add_column('comment', sa.Column('pos_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['pos_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'timestamp')
    op.drop_column('comment', 'pos_id')
    op.drop_column('comment', 'language')
    # ### end Alembic commands ###
